### PR TITLE
Adding China UnionPay + some general warnings

### PR DESCRIPTION
**Pull request by austinhuang0131**
Since you have JCB, I think UnionPay should equally be on there.

### CODE REVIEW

**Comment by Changaco** [comment]
UnionPay isn't in the list because it's a subrange, and we don't include subranges because there are too many of them and I don't know of any exhaustive public list.

**Comment by austinhuang0131** [comment]
Not really.

* UnionPay accepts international merchants independently. It is, in fact, not just a fork off Discover (eg. `65` cards from BC Card in South Korea and RuPay in India). Its American acceptance is steadily growing.
* UnionPay issuers are in most East Asian countries, not just China.

**Comment by Changaco** [comment]
I meant that UnionPay's `62` is a subrange of Maestro's `6`, and if we include subranges then we would need to use a more advanced lookup algorithm than a list of regular expressions, otherwise it's going to become a mess.

**Comment by austinhuang0131** [comment]
UnionPay is credit cards.

**Pull request merged**
